openapi: 3.0.1
info:
  title: Leave Management
  version: 0.0.1
  description: |-
    Leave management is a web application where a user can request leave.
    The request will reach the approver via email (using SES).
    The approver can either reject or approve the leave request, and a response will be sent to the user.

paths:
  /apply-leave:
    post:
      summary: User can send a leave request
      description: |-
        This endpoint allows the user to send a leave request by providing required fields in the body.
        Authorization with a valid JWT token is required.
      security:
        - LambdaAuthorizer: []
      parameters:
        - name: Authorization
          in: header
          required: true
          description: JWT token
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/leaveRequest"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request

components:
  securitySchemes:
    LambdaAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authorizer:
        type: request
        authorizerUri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:LeaveAuthorizerFunction/invocations
        authorizerPayloadFormatVersion: 2.0
        identitySource: "$request.header.Authorization"
        enableSimpleResponses: true

  schemas:
    leaveRequest:
      type: object
      description: Leave request JSON body
      additionalProperties: false
      required:
        - employeeEmail
        - startDate
        - endDate
      properties:
        employeeEmail:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        leaveType:
          type: string
        approverEmail:
          type: string
