swagger: "2.0"
info:
  title: "LeaveAPi"
  version: "1.0"
paths:
  /apply-leave:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: "200 response"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:states:action/StartExecution
        httpMethod: POST
        type: aws
        credentials:
          Fn::GetAtt: [RestApiRole, Arn]
        requestTemplates:
          application/json: |
            {
              "input": "$util.escapeJavaScript($input.body)",
              "stateMachineArn": "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:leaveStateMachine"
            }
        responses:
          default:
            statusCode: "200"